apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "frontend.uname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
data:
  default.conf: |+
    server {
        listen 80;
        server_name codo.opendevops.cn;
        
        add_header Cache-Control no-cache;
        # 开启gzip压缩
        gzip on;
        gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;
        gzip_min_length 1024;
        gzip_vary on;
        gzip_proxied any;
        gzip_comp_level 6;
        gzip_buffers 16 8k;
        
        location / {
            # 确保每次请求都带上时间戳，避免浏览器缓存
            if ($request_filename ~* ^.*?\.(html|htm)$) {
                add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate";
                add_header Pragma no-cache;
                expires -1;
            }
            proxy_http_version 1.1;
            add_header Access-Control-Allow-Methods *;
            add_header Access-Control-Max-Age 3600;
            add_header Access-Control-Allow-Credentials true;
            add_header Access-Control-Allow-Origin $http_origin;
            
            root /data/h5/home-index/;
            index index.html index.htm;
            try_files $uri $uri/ /index.html;
        }

        # 落地页
        location /index/ {
            # 确保每次请求都带上时间戳，避免浏览器缓存
            if ($request_filename ~* ^.*?\.(html|htm)$) {
                add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate";
                add_header Pragma no-cache;
                expires -1;
            }
            proxy_http_version 1.1;
            add_header Access-Control-Allow-Methods *;
            add_header Access-Control-Max-Age 3600;
            add_header Access-Control-Allow-Credentials true;
            add_header Access-Control-Allow-Origin $http_origin;
            
            alias /data/h5/landing-f/;
            index index.html index.htm;
            try_files $uri $uri/ /index/index.html;
        }

        # 重定向 /index 到 /index/
        location = /index {
            return 301 /index/;
        }

        location /web/cmdb/ {
            # 确保每次请求都带上时间戳，避免浏览器缓存
            if ($request_filename ~* ^.*?\.(html|htm)$) {
                add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate";
                add_header Pragma no-cache;
                expires -1;
            }
            proxy_http_version 1.1;
            add_header Access-Control-Allow-Methods *;
            add_header Access-Control-Max-Age 3600;
            add_header Access-Control-Allow-Credentials true;
            add_header Access-Control-Allow-Origin $http_origin;
            
            alias /data/h5/cmdb-f/;
            index index.html index.htm;
            try_files $uri $uri/ /index.html;
        }

        location /web/kerrigan/ {
            # 确保每次请求都带上时间戳，避免浏览器缓存
            if ($request_filename ~* ^.*?\.(html|htm)$) {
                add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate";
                add_header Pragma no-cache;
                expires -1;
            }
            proxy_http_version 1.1;
            add_header Access-Control-Allow-Methods *;
            add_header Access-Control-Max-Age 3600;
            add_header Access-Control-Allow-Credentials true;
            add_header Access-Control-Allow-Origin $http_origin;
            
            alias /data/h5/kerrigan-f/;
            index index.html index.htm;
            try_files $uri $uri/ /index.html;
        }

        location /web/flow/ {
            # 确保每次请求都带上时间戳，避免浏览器缓存
            if ($request_filename ~* ^.*?\.(html|htm)$) {
                add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate";
                add_header Pragma no-cache;
                expires -1;
            }
            proxy_http_version 1.1;
            add_header Access-Control-Allow-Methods *;
            add_header Access-Control-Max-Age 3600;
            add_header Access-Control-Allow-Credentials true;
            add_header Access-Control-Allow-Origin $http_origin;
            
            alias /data/h5/flow-f/;
            index index.html index.htm;
            try_files $uri $uri/ /web/flow-f/index.html;
        }

        location /web/gw/ {
            # 确保每次请求都带上时间戳，避免浏览器缓存
            if ($request_filename ~* ^.*?\.(html|htm)$) {
                add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate";
                add_header Pragma no-cache;
                expires -1;
            }
            proxy_http_version 1.1;
            add_header Access-Control-Allow-Methods *;
            add_header Access-Control-Max-Age 3600;
            add_header Access-Control-Allow-Credentials true;
            add_header Access-Control-Allow-Origin $http_origin;
            
            alias /data/h5/tianmen-f/;
            index index.html index.htm;
            try_files $uri $uri/ /web/tianmen-f/index.html;
        }

        location /web/noc/ {
            # 确保每次请求都带上时间戳，避免浏览器缓存
            if ($request_filename ~* ^.*?\.(html|htm)$) {
                add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate";
                add_header Pragma no-cache;
                expires -1;
            }
            proxy_http_version 1.1;
            add_header Access-Control-Allow-Methods *;
            add_header Access-Control-Max-Age 3600;
            add_header Access-Control-Allow-Credentials true;
            add_header Access-Control-Allow-Origin $http_origin;
            
            alias /data/h5/notice-f/;
            index index.html index.htm;
            try_files $uri $uri/ /web/notice-f/index.html;
        }

        location /web/mg/ {
            # 确保每次请求都带上时间戳，避免浏览器缓存
            if ($request_filename ~* ^.*?\.(html|htm)$) {
                add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate";
                add_header Pragma no-cache;
                expires -1;
            }
            proxy_http_version 1.1;
            add_header Access-Control-Allow-Methods *;
            add_header Access-Control-Max-Age 3600;
            add_header Access-Control-Allow-Credentials true;
            add_header Access-Control-Allow-Origin $http_origin;
            
            alias /data/h5/adminv4-f/;
            index index.html index.htm;
            try_files $uri $uri/ /web/adminv4-f/index.html;
        }

        location /web/servermgmt/ {
            # 确保每次请求都带上时间戳，避免浏览器缓存
            if ($request_filename ~* ^.*?\.(html|htm)$) {
                add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate";
                add_header Pragma no-cache;
                expires -1;
            }
            proxy_http_version 1.1;
            add_header Access-Control-Allow-Methods *;
            add_header Access-Control-Max-Age 3600;
            add_header Access-Control-Allow-Credentials true;
            add_header Access-Control-Allow-Origin $http_origin;
            
            alias /data/h5/server-management-f/;
            index index.html index.htm;
            try_files $uri $uri/ /web/servermgmt/index.html;
        }

        location /web/cnmp/ {
            # 确保每次请求都带上时间戳，避免浏览器缓存
            if ($request_filename ~* ^.*?\.(html|htm)$) {
                add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate";
                add_header Pragma no-cache;
                expires -1;
            }

            proxy_http_version 1.1;
            add_header Access-Control-Allow-Methods *;
            add_header Access-Control-Max-Age 3600;
            add_header Access-Control-Allow-Credentials true;
            add_header Access-Control-Allow-Origin $http_origin;
            
            alias /data/h5/cnmp-f/;
            index index.html index.htm;
            try_files $uri $uri/ /web/cnmp/index.html;
        }

        location /api/cnmp-ws/ {
            # WebSocket 支持
            proxy_read_timeout 600s;                 
            proxy_send_timeout 600s;        

            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;         
            client_max_body_size 1000m;
            proxy_redirect off;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Scheme $scheme;
            proxy_pass http://{{ template "gateway.innerApi" . }}/api/cnmp-ws/;
        }

        location /api/ {
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            
            client_max_body_size 1000m;
            proxy_redirect off;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Scheme $scheme;
            proxy_pass http://{{ template "gateway.innerApi" . }}/api/;
        }
    }

